### PR TITLE
Replace redbox-react with delicate-error-reporter

### PR DESCRIPTION
**Pull request by danmartinez101**
As mentioned in #8, redbox-react seems not to be actively maintained and currently does not work with Safari. 

I'll look into submitting a PR to resolve https://github.com/KeywordBrain/redbox-react/issues/8 but in the meantime, delicate-error-reporter might be a viable alternative.

### CODE REVIEW

**Comment by bebraw** [comment]
Any chance you could look into this? There isn't any action going on at redbox still.

**Comment by danmartinez101** [comment]
I'll make a decision on this within the week depending on how things go with the PR.

**Comment by danmartinez101** [comment]
@bebraw The PR was merged just now and a release cut. I'll have a release out within 24 hours with the update.

**Comment by danmartinez101** [comment]
@bebraw let me know if you run into any issues with this and I'll take a look.

Released: https://github.com/danmartinez101/babel-preset-react-hmre/releases/tag/v1.1.0

**Comment by bebraw** [comment]
Thanks! Seems to work well based on a quick test. :+1:

**Pull request closed without merging**
